plugins:
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
      num_cubes: 10
      ns: r-
      stop: 600
  frequency: 30
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: db.docker.wambacloud.com
      port: 15867
      namespace: test
      stop: 700
      write:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
  frequency: 30
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: db.docker.wambacloud.com
      port: 15867
      namespace: test
      read:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
  frequency: 30
