plugins:
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: 172.17.0.5
      port: 15867
      namespace: test
      stop: 10000
      write:
        - property: shape
        - property: pose
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 1
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: 172.17.0.5
      port: 15867
      namespace: test
      read:
        - property: shape
        - property: pose
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 2
