plugins:
- name: sync_server_plugin
  lib: libed_sync_server_plugin.so
  frequency: 20
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
      num_cubes: 100
  frequency: 20
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: db.docker.wambacloud.com
      port: 15867
      namespace: test
      stop: 10000
  frequency: 20
