externals:
- name: amigo
plugins:
#- name: hypertable_writer_plugin
#  lib: libed_hypertable_writer_plugin.so
#  parameters:
#      address: 172.17.0.1
#      port: 15867
#      namespace: test
#      stop: 10000
#      write:
#        - property: shape
#        - property: pose
#        - property: convex_hull
#        - property: type
#  frequency: 1
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: 172.17.0.1
      port: 15867
      namespace: test
      read:
        - property: shape
        - property: pose
        - property: convex_hull
        - property: type
  frequency: 1
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
       num_cubes: 10
       ns: r
       stop: 400
       measurement_width: 100
       measurement_height: 100
  frequency: 5
#- name: kinect_integration
#  lib: libed_kinect2_plugin.so
#  enabled: 1
#  parameters:
#      debug: 0
#      continuous: 0
#      topic: /rgbd
#      max_correspondence_distance: 0.1
#      max_range: 3.0
#      downsample_factor: 2
