plugins:
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
      num_cubes: 100
      ns: r-
      stop: 400
      measurement_width: 100
      measurement_height: 100
  frequency: 5
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: 172.17.0.1
      port: 15867
      namespace: test
      stop: 1000
      write:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 5
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: 172.17.0.1
      port: 15867
      namespace: test
      read:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 5
