plugins:
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
      num_cubes: 500
      ns: r-
      stop: 700
  frequency: 10
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: 172.17.0.3
      port: 15867
      namespace: test
      stop: 1000
      write:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 10
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: 172.17.0.3
      port: 15867
      namespace: test
      read:
        - property: pose
        - property: shape
        - property: convex_hull
        - property: type
        - property: measurement
  frequency: 10
