plugins:
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters:
      num_cubes: 10
      ns: r-
      stop: 603
  frequency: 30
- name: hypertable_writer_plugin
  lib: libed_hypertable_writer_plugin.so
  parameters:
      address: db.docker.wambacloud.com
      port: 15867
      namespace: test
      stop: 700
  frequency: 30
- name: hypertable_reader_plugin
  lib: libed_hypertable_reader_plugin.so
  parameters:
      address: db.docker.wambacloud.com
      port: 15867
      namespace: test
      frequency: 30
