world_name: robotics_testlabs

plugins:
- name: sync_server_plugin
  lib: libed_sync_server_plugin.so
  frequency: 10
- name: bouncing_cubes
  lib: libed_bouncing_cubes.so
  parameters
      num_cubes: 1000
  frequency: 10
